apiVersion: v1                      # API Version, manifest always begins with it and its version
kind: Namespace                     # Kind of Object
metadata:                           # Helpful data to identify the Object
  name: testenv                     # Name of the Namespace
  labels:                           # Identifying attributes of Objects that are meaningful and relevant to users
    environment: testenv            # Name and Value of the Label
    
