apiVersion: v1              # API Version, manifest always begins with it and its version
kind: Namespace             # Kind of Object
metadata:                   # Helpful data to identify the Object
  name: testenv             # Nmae of the Namespace
  labels:                   # Identifying attributes of Oobjects that are meaningful and relevant to users
    name: testenv           # Name of the Label

