apiVersion: v1                      # API Version, manifest always begins with it and its version
kind: Pod                           # Kind of Object
metadata:                           # Helpful data to identify the Object
  name: l8-pod                      # Name of the Pod
  labels:                           # Set of labels
    environment: testenv
    app: httpd
spec:                               # Description of the characteristics to be obtained from the resource
  containers:                       # List of Containers
    - name: l8-container            # Name of the Container
      image: httpd:latest           # Image to use
      ports:                        # List of the Container's ports
        - containerPort: 80         # The Container port
        
