apiVersion: v1                      # API Version, manifest always begins with it and its version
kind: Service                       # Kind of Object
metadata:                           # Helpful data to identify the Object
  name: l8-service                  # Name of the Service
spec:                               # Description of the characteristics to be obtained from the resource
  selector:                         # Selector is a way to match a set of resources based on their labels
                                    # The selector field helps to specify the pods that the service should route traffic to
    environment: testenv            # Matches pods with these labels
    app: apache2                    #
  ports:                            # Port configuration
    - protocol: TCP                 # Protocol to use
      port: 8080                    # The port exposed by the service
      targetPort: 80                # The port on the pods that the service routes to
      nodePort: 38088               # The port on each node to expose the service
  type: NodePort                    # Type of Service.
                                    # ClusterIP is a default type, makes the service accessible only within the Kubernetes cluster
                                    # NodePort - application to be accessible externally from the host operating system
