service:
  ssh:
    type: NodePort

ingress:
  enabled: true
  className: "public"
  annotations:
    cert-manager.io/issuer: "selfsigned-cluster-issuer"
    kubernetes.io/ingress.class: "public"
  hosts:
    - # -- Host address. Helm template can be passed.
      host: gitea.k8s.loc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tls-secret
      hosts:
        - gitea.k8s.loc

persistence:
  enabled: true

gitea:
  admin:
    username: testadmin
    password: test
    email: "test@k8s.loc"
  additionalConfigFromEnvs:
    - name: ENV_TO_INI__DATABASE__HOST
      value: gitea-postgresql
  config:
    service:
      DISABLE_REGISTRATION: true
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
    livenessProbe:
      failureThreshold: 30
    readinessProbe:
      failureThreshold: 30

redis-cluster:
  enabled: false

postgresql-ha:
  enabled: false

